baseURL = 'https://seyoungjeong.github.io/'
relativeURLs = true
languageCode = 'ko-KR'
title = "Seyoung's Out Of The Office"
theme = 'hugo-bearblog'

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS"]

[author]
  name = "Seyoung Jeong"

[params]
  description = "Seyoung Jeong's blog"
  dateFormat = "2006-01-02"
  hideMadeWithLine = true

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 30

[[menu.main]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"
  weight = 40
