baseURL = 'https://seyoungjeong.github.io/'
relativeURLs = true
languageCode = 'ko-KR'
title = "<Seyoung Jeong>"
theme = 'PaperMod'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[author]
  name = "Seyoung Jeong"

[params]
  defaultTheme = 'dark'
  disableThemeToggle = true
  ShowCodeCopyButtons = true
  author = "Seyoung Jeong"

[[menu.main]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"
  weight = 10

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 30

[[menu.bottom]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.bottom]]
  identifier = "bmm"
  name = "BMM"
  url = "/categories/bmm/"
  weight = 20

[[menu.bottom]]
  identifier = "coding"
  name = "Coding"
  url = "/categories/coding/"
  weight = 30

[[menu.bottom]]
  identifier = "etc"
  name = "ETC"
  url = "/categories/etc/"
  weight = 40

[[menu.bottom]]
  identifier = "ski"
  name = "Ski"
  url = "/categories/ski/"
  weight = 50

[[menu.bottom]]
  identifier = "travel"
  name = "Travel"
  url = "/categories/travel/"
  weight = 60
